_wandb:
    value:
        cli_version: 0.25.0
        e:
            wmipop5pj5sss5koqcge8zhuumq5i49t:
                apple:
                    ecpuCores: 4
                    gpuCores: 10
                    memoryGb: 8
                    name: Apple M2
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "4831838208"
                codePath: transformer/train/train.py
                codePathLocal: transformer/train/train.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "244964147200"
                email: yhp2378@gmail.com
                executable: /Users/yash/ml-infra/inference-serving-infra/.venv/bin/python3
                git:
                    commit: cdaf03ffbcfad69060b6774226d73f9b958be0bf
                    remote: https://github.com/yashp5/inference-serving-infra.git
                host: yashs-MacBook-Air.local
                memory:
                    total: "8589934592"
                os: macOS-15.5-arm64-arm-64bit-Mach-O
                program: /Users/yash/ml-infra/inference-serving-infra/transformer/train/train.py
                python: CPython 3.13.5
                root: /Users/yash/ml-infra/inference-serving-infra
                startedAt: "2026-03-31T22:35:16.216657Z"
                writerId: wmipop5pj5sss5koqcge8zhuumq5i49t
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 16
            "4": 3.13.5
            "5": 0.25.0
            "12": 0.25.0
            "13": darwin-arm64
batch_size:
    value: 64
block_size:
    value: 256
dropout:
    value: 0.2
epochs:
    value: 1
eval_batches:
    value: 300
learning_rate:
    value: 0.0003
log_interval:
    value: 500
n_embd:
    value: 384
n_head:
    value: 6
n_layer:
    value: 6
